name: Deploy to GitHub Pages

permissions:
 contents: write

on:
 push:
  branches:
   - main

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout code
     uses: actions/checkout@v4

   - name: Set up Node.js
     uses: actions/setup-node@v4
     with:
      node-version: "20"

   - name: Install dependencies
     run: npm ci

   - name: Build project
     run: npm run build

   - name: Configure Git user and URL rewrite
     run: |
      git config --global user.email "jero@uppertech.net"
      git config --global user.name "jero-uppertech"
      # This uses the GH_TOKEN which will be available from the 'env' block below
      git config --global url."https://${GH_TOKEN}@github.com/".insteadOf "https://github.com/"
     env:
      # Use the built-in GitHub Token for authentication
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

   - name: Run deploy
     env:
      # Pass the same built-in GitHub Token to your deploy script (assuming it's gh-pages)
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     run: npm run deploy
